name: Test Custom Action

on:
  workflow_dispatch:  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run custom action
        uses: ./.github/actions/hello-action
        with:
          name: "Parandhaman"