name: Using Reusable Workflow
on:
  push:
    branches:
      - main
jobs:
  deploy:
    uses: ./.github/workflows/reusable.yml
    with:
      artifact-name : "new-dist"
    # secrets:
    #   some-secret: ${{ secrets.some-secret }}

  print-deploy-result:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: print deploy output
        run: echo "${{ needs.deploy.outputs.result }}"